[package]
name = "bevy_kira_audio"
version = "0.5.1"
authors = ["Niklas Eicker <hello@nikl.me>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "Bevy plugin for dynamic audio"
repository = "https://github.com/NiklasEi/bevy_kira_audio"
homepage = "https://github.com/NiklasEi/bevy_kira_audio"
documentation = "https://docs.rs/bevy_kira_audio"
keywords = ["bevy", "gamedev", "audio", "music"]
categories = ["game-development", "multimedia::audio"]
readme = "./README.md"
resolver = "2"

[features]
mp3 = ["kira/mp3"]
ogg = ["kira/ogg"]
flac = ["kira/flac"]
settings_loader = ["ron", "serde"]
wav = ["kira/wav"]

[dependencies]
# bevy
bevy = { git = "https://github.com/bevyengine/bevy", branch = "main", default-features = false }
bevy_reflect = { git = "https://github.com/bevyengine/bevy", branch = "main", default-features = false }
bevy_utils = { version = "0.5.0", default-features = false }

# other
anyhow = "1.0"
kira = { version = "0.5.2", default-features = false }
parking_lot = "0.11.0"
ron = { version = "0.6.2", optional = true }
serde = { version = "1.0", features = ["derive"], optional = true }

[dev-dependencies]
winit = "0.24.0"
bevy = { git = "https://github.com/bevyengine/bevy", branch = "main", features = ["bevy_gltf", "bevy_winit", "render", "bevy_wgpu"] }

[[example]]
name = "basic"
path = "examples/basic.rs"
required-features = ["ogg"]

[[example]]
name = "stream"
path = "examples/stream.rs"

[[example]]
name = "semantic_duration"
path = "examples/semantic_duration.rs"
required-features = ["ogg", "settings_loader"]
